INSERT INTO user_management.thirdeye_permission ( permission_name, permission_desc )
VALUES ("APP_LOGIN","Root permission to allow the user to login to the application"),    
("USER_MODIFY ","Ability to create / modify a user"),
("USER_VIEW ","Ability to view users in the system"),
("USER_ROLE_VIEW","Ability to view users roles in the system"),
("USER_ROLE_MODIFY","Ability to modify the permissions associated to the roles"),
("TEMPLATE_VIEW","Ability to VIEW asset templates in the system"),
("TEMPLATE_MODIFY","Ability to create asset templates in the system"),
("ASSET_FILLDETAILS","Allow the user to fill the asset details"),
("REPORT_ASSET_GRAPH","Allow the user to create and view asset graphs"),
("REPORT_SCATTER_GRAPH","Allow user to extract scatter graph reports"),
("REPORT_FACET_GRAPH","Allow user to extract reports on the facets of the questionnaire"),
("REPORT_PHP","Allow user to extract portfolio health on a page reports"),
("REPORT_FUNCTIONAL_REDUNDANCY","Allow user to extract functional redundancy on a page reports"),
("REPORT_WAVE_ANALYSIS","Allow user to extract Wave Analysis reports"),
("REPORT_TREND_ANALYSIS","Allow user to extract Trend Analysis reports"),
("WORKSPACES_MODIFY","Allow the user to create and modify workspace access"),
("WORKSPACES_VIEW","Allow the user to view details about a workspace"),
("WORKSPACES_VIEW_DASHBOARD","View the dashboards in the workspace"),
("WORKSPACES_MODIFY_DASHBOARD","Add or Modify the dashboards in the workspace"),
("QUESTION_MODIFY","Allow the user to create and modify questions"),
("QUESTION_VIEW","Allow the user to view questions"),
("QUESTIONNAIRE_MODIFY","Allow the user to create and modify questionnaires"),
("QUESTIONNAIRE_VIEW","Allow the user to view questionnaires"),
("QUESTIONNAIRE_RESPOND","Allow the user to respond to questionnaires"),
("AID_MODIFY","Allow the user to create and modify Application Interface Diagram"),
("AID_VIEW","Allow the user to view Application Interface Diagram"),
("BCM_MODIFY","Allow the user to create and modify Business Capability Map"),
("BCM_VIEW","Allow the user to view Business Capability Map"),
("RELATIONSHIP_MODIFY","Allow the user to create and modify Relationship"),
("RELATIONSHIP_VIEW","Allow the user to view Relationship"),
("PARAMETER_MODIFY","Allow the user to create and modify parameters"),
("PARAMETER_VIEW","Allow the user to view parameters"),
("BOOST_EVALUATED_VALUE","Allow the user to boost parameter evaluated value"),
("FUNCTIONAL_MAP_MODIFY","Allow the user to create and modify functional maps"),
("FUNCTIONAL_MAP_VIEW","Allow the user to view functional maps"),
("COLOR_SCHEME_MODIFY","Allow the user to create and modify color schemes"),
("COLOR_SCHEME_VIEW","Allow the user to view color schemes"),
("INDEX_CREATION","Allow the user to create Elastic Search index"),
("VIEW_TCO","Allow the user to view TCO Parameter"),
("MODIFY_TCO","Allow the user to modify TCO Parameter"),
("BENCHMARK_MODIFY","Allow the user to modify Benchmark"),
("BENCHMARK_VIEW","Allow the user to view Benchmark"),
("SNOW_VIEW","Allow the user to view data from Service Now"),
("ADMIN_VIEW","Allow the user to view all the reports"),
("GNG_VIEW","Allow the user to view Asset GO/No-Go Analysis"),
("ASSET_TYPE_MANAGEMENT","Allow user to view Asset Type Management"),
("DELETE_ASSET_TYPE","Allow user to delete asset type"),
("DELETE_USER_ROLE","Allow user to delete user role"),
("DELETE_QUESTIONNAIRE","Allow user to delete questionnaire"),
("DELETE_WORKSPACE","Allow the user to delete workspace"),
("SAVE_EDIT_DELETE_REPORT","Allow the user to save,edit and delete their own reports"),
("VIEW_SAVED_REPORT","Allow the user to view all assigned and saved reports"),
("VIEW_ASSET_AUDIT_TRAIL","Allow admin to see the asset audit trail report"),
("VIEW_DENSITY_HEAT_MAP","Allow admin to see the density heat map"),
("VIEW_CIO","Allow cio to see the bcm cio"),
("VIEW_CLOUD_GONO","Allow user to see the cloud report GONOGO"),
("VIEW_CLOUD_PARAMETERHEATMAP","Allow user to see the cloud report Parameter Heatmap"),
("VIEW_LIFECYCLE_REPORT","Allow the user to view LifeCycle Report");

INSERT INTO user_management.thirdeye_role ( role_name, role_description )
 VALUES ("ROLE_APP_ADMIN","ROLE_APP_ADMIN"),
("ROLE_APP_USER","ROLE_APP_USER"),
("ROLE_CONSULTANT","ROLE_CONSULTANT"),
("ROLE_CUSTOMER","ROLE_CUSTOMER"),
("ROLE_CIO","ROLE_CIO");
 

INSERT INTO user_management.thireye_workspace ( workspace_name, workspace_desc )
   VALUES( "TESTING","TESTING"),
   ( "TESTING1","TESTING1"),
   ( "TESTING2","TESTING2");
